services:
  bragabot:
    image: fernandopereira3/bragabot:latest
    platform: linux/arm64
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - bragabot:/app/users
    restart: unless-stopped

volumes:
  bragabot:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/samba/programas/Volumes/braga_bot